name: Security Analysis

on:
  push:
    branches:
      - master

jobs:
  run-shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Shellcheck
        run: sudo apt-get install shellcheck
         
      - name: Scan all .sh files with Shellcheck
        run: |
          find . -name "*.sh" | xargs shellcheck
