name: ShellCheck

on: push

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install ShellCheck
        run: sudo apt-get install shellcheck -y

      - name: Run ShellCheck
        run: find . -type f -name "*.sh" | xargs shellcheck
